function mia_build


dirname = ['C:\Users\cxyka\OneDrive - brandeis.edu\Brandeis\research\2021 fall\vhlab-ArrayTomography-matlab'];

m=vlt.matlab.mfiledirinfo(dirname);

rt = vlt.matlab.packagenamereplacementtable(m,dirname,'mia');
%'.at_colocalization_editors.','.colocalization.editors.', ...
%'.at_colocalization_makers.','.colocalization.makers.', ...
%'.at_roi_editors.','.roi.editors.', ...
%'.at_roi_functions.','.roi.functions.', ...
%'.at_roi_makers.','.roi.makers.', ...
search_replace = { ...
    '.at_analysis.','.analysis.', ...
    '.at_colocalization.','.colocalization.', ...
    '.at_exporters.','.exporters.', ...
    '.at_image.','.image.', ...
    '.at_image_process.','.image.process.', ...
    '.at_pipelines.','.pipelines.', ...
    '.at_roi.','.roi.', ...
    '.at_scaler.','.scaler.', ...
    '.at_toydata.','.toydata.', ...
    '.at_utilities.','.utilities.', ...
};

for i=1:numel(rt),
	for j=1:2:numel(search_replace),
		rt(i).replacement = strrep(rt(i).replacement,search_replace{j},search_replace{j+1});
	end;
end;

fuse = vlt.matlab.findfunctionusedir([dirname filesep '+mia'],m);

%status = vlt.matlab.replacefunction(fuse,rt);

% when you're ready to really run it
status = vlt.matlab.replacefunction(fuse,rt,'Disable',0);


